name: tInteractions
version: '${project.version}'
main: tanko.tinteractions.TInteractions
api-version: 1.19
depend: [Citizens]
commands:
  interactions:
    description: interactions command
    usage: /<command>
    permission: tinteractions.commands
  requirements:
    description: requirements command
    usage: /<command>
    permission: tinteractions.commands
  ti:
    description: text command
    usage: /<command>
    permission: tinteractions.commands.ti